### ISSUE TITLE
Fix display mismatches in firefox and utterly total chaos in webkit

### ISSUE THREAD

**Issue by apazureck** [apazureck/registermaschine#2]
The registermaschine is not displayed correctly in those two browsers.

**Comment by UraniumDonut** [comment]
Should be fixed in #3 
Before:
![image](https://user-images.githubusercontent.com/75068550/148966488-d161a120-362e-4a84-bbe7-5b86a8c72564.png)
![image](https://user-images.githubusercontent.com/75068550/148966594-06df7c46-8581-48d3-9579-577a3ebf0532.png)
